spring.h2.console.enabled: true
spring.h2.console.path: /h2
logging.level.org.hibernate.SQL: debug

spring.datasource.url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
spring.datasource.driverClassName: org.h2.Driver